Repository reynan-dev/codenaute, pull requests merged in 2023-08, with the labels that each got.

#76 chore(Makefile): updating echos and makefiles commands
  Makefile
  client/Makefile
  database/Makefile
Labels: development/setup

#83 ci: implementing deploy to production
  .github/PULL_REQUEST_TEMPLATE/pr_template.md
  .github/PULL_REQUEST_TEMPLATE/relase_template.md
  .github/pull_request_template.md
  .github/workflows/client.yml
  .github/workflows/release-tag.yml
  .github/workflows/server.yml
  README.md
  client/.dockerignore
  client/Dockerfile
  client/codegen.ts
  client/pnpm-lock.yaml
  client/src/index.tsx
  docker-compose.yml
  package.json
  server/.dockerignore
  server/package.json
  server/pnpm-lock.yaml
  server/src/utils/configs/database.ts
  server/src/utils/configs/server.ts
  server/src/utils/methods/catchErrors.ts
  server/src/utils/methods/getErrorMessage.ts
  server/tsconfig.json
Labels: development/setup

#90 v0.2.0
  .github/PULL_REQUEST_TEMPLATE/pr_template.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  .github/pull_request_template.md
  .github/workflows/client.yml
  .github/workflows/release-tag.yml
  .github/workflows/server.yml
  README.md
  client/.dockerignore
  client/Dockerfile
  client/codegen.ts
  client/pnpm-lock.yaml
  client/src/index.tsx
  docker-compose.yml
  package.json
  pnpm-lock.yaml
  server/.dockerignore
  server/package.json
  server/pnpm-lock.yaml
  server/src/models/Project.ts
  server/src/resolvers/ProjectResolver.ts
  server/src/resolvers/args/ProjectArgs.ts
  server/src/utils/configs/database.ts
  server/src/utils/configs/server.ts
  server/src/utils/methods/catchErrors.ts
  server/src/utils/methods/getErrorMessage.ts
  server/tsconfig.json
Labels: release/minor

#91 fix(ci): release tag workflow
  .github/workflows/release-tag.yml
Labels: release/patch

#92 v0.1.0
  .github/workflows/release-tag.yml
Labels: release/minor

#94 fix: returning boolean when delete member account
  client/src/pages/account/account.graphql.ts
  server/src/resolvers/MemberResolver.ts
Labels: development/app

#98 fix(server): updating project name regex to include spaces
  server/src/utils/enums/Validations.ts
Labels: development/app

#100 feat(server): set import as relative path on models
  server/src/models/Member.ts
  server/src/models/Project.ts
  server/src/models/Session.ts
Labels: development/app

#102 fix(server): implement auto run migrations when deploy or test
  server/src/utils/configs/database.ts
  server/tests/setup.jest.ts
Labels: development/app

#103 build: removing redis container
  database/Makefile
  docker-compose.yml
  docs/database_model.png
Labels: development/setup

#105 feat(ci): include mobile workflow
  .github/workflows/mobile.yml
  Makefile
  client/pnpm-lock.yaml
  mobile/package-lock.json
  mobile/pnpm-lock.yaml
  pnpm-lock.yaml
  server/pnpm-lock.yaml
Labels: development/setup

#107 fix(client): removing setVisibeFile to fix Max depth exceeded error and visual bug of open project
  client/package.json
  client/src/graphql/__generated__/gql.ts
  client/src/graphql/__generated__/graphql.ts
  client/src/pages/code/code.graphql.ts
  client/src/pages/code/code.page.tsx
  client/src/pages/code/code.service.tsx
Labels: development/app

#108 feat(client): include set as main file on file explorer
  client/src/context/project/project.context.tsx
  client/src/helpers/has-sandpack-files-changed.ts
  client/src/pages/code/_components/context-menu.tsx
  client/src/pages/code/_components/custom-file-explorer.tsx
  client/src/pages/code/_components/sandpack.container.tsx
  client/src/pages/code/_helpers/rename-file.ts
  client/src/pages/code/code.service.tsx
Labels: development/app

#109 v0.2.0
  client/package.json
  client/src/context/project/project.context.tsx
  client/src/graphql/__generated__/gql.ts
  client/src/graphql/__generated__/graphql.ts
  client/src/helpers/has-sandpack-files-changed.ts
  client/src/pages/account/account.graphql.ts
  client/src/pages/code/_components/context-menu.tsx
  client/src/pages/code/_components/custom-file-explorer.tsx
  client/src/pages/code/_components/sandpack.container.tsx
  client/src/pages/code/_helpers/rename-file.ts
  client/src/pages/code/code.graphql.ts
  client/src/pages/code/code.page.tsx
  client/src/pages/code/code.service.tsx
  client/src/pages/my-projects/_components/filter-bar.tsx
  client/src/pages/my-projects/helpers/search-projects.ts
  database/Makefile
  docker-compose.yml
  docs/database_model.png
  server/src/models/Member.ts
  server/src/models/Project.ts
  server/src/models/Session.ts
  server/src/resolvers/MemberResolver.ts
  server/src/utils/enums/Validations.ts
Labels: release/minor

#84 chore(mobile): init app setup with poc
  .github/workflows/mobile.yml
  .npmrc
  Makefile
  README.md
  client/pnpm-lock.yaml
  mobile/.gitignore
  mobile/Makefile
  mobile/app.config.js
  mobile/app.json
  mobile/babel.config.js
  mobile/codegen.ts
  mobile/package-lock.json
  mobile/package.json
  mobile/pnpm-lock.yaml
  mobile/postcss.config.js
  mobile/src/app.tsx
  mobile/src/assets/adaptive-icon.png
  mobile/src/assets/favicon.png
  mobile/src/assets/icon.png
  mobile/src/assets/splash.png
  mobile/src/components/members.tsx
  mobile/src/gql/__generated__/fragment-masking.ts
  mobile/src/gql/__generated__/gql.ts
  mobile/src/gql/__generated__/graphql.ts
  mobile/src/gql/__generated__/index.ts
  mobile/src/gql/operations/create-project.graphql.ts
  mobile/src/gql/operations/get-all-members.graphql.ts
  mobile/src/index.ts
  mobile/src/styles/__generated__/nativewind-output.js
  mobile/src/styles/__generated__/tailwind.output.css
  mobile/src/styles/app.d.ts
  mobile/src/styles/colors.js
  mobile/src/styles/global.css
  mobile/src/styles/plugins/color-vars-extractor.js
  mobile/tailwind.config.js
  mobile/tsconfig.json
  pnpm-lock.yaml
  server/pnpm-lock.yaml
Labels: development/setup

#99 feat(server): implement migration
  server/Makefile
  server/package.json
  server/pnpm-lock.yaml
  server/src/migrations/1668617228646-default.ts
  server/src/seeds/index.ts
  server/src/utils/commands/codenaute-cli.ts
  server/src/utils/configs/database.ts
  server/src/utils/migrations/1691581386772-codenaute.ts
  server/src/utils/seeds/index.ts
  server/src/utils/seeds/member.seeds.ts
  server/src/utils/seeds/project.seeds.ts
  server/src/validators/isSandpackFiles.ts
  server/tests/setup.jest.ts
Labels: development/setup

#101 refactor: updating Project.main to Project.mainFile
  client/src/context/project/project.context.tsx
  client/src/fixtures/projects-fixtures.ts
  client/src/graphql/__generated__/gql.ts
  client/src/graphql/__generated__/graphql.ts
  client/src/pages/code/_components/custom-file-explorer.tsx
  client/src/pages/code/_components/sandpack.container.tsx
  client/src/pages/code/code.graphql.ts
  client/src/pages/code/code.service.tsx
  client/src/pages/create-project/create-project.graphql.ts
  client/src/pages/create-project/create-project.page.tsx
  client/src/pages/create-project/create-project.service.tsx
  client/src/pages/my-projects/my-projects.graphql.ts
  client/src/pages/my-projects/my-projects.page.tsx
  client/src/pages/my-projects/my-projects.service.tsx
  client/src/types/project.ts
  mobile/package-lock.json
  mobile/src/gql/__generated__/gql.ts
  mobile/src/gql/__generated__/graphql.ts
  mobile/src/screens/last-projects/_components/project-card.tsx
  mobile/src/screens/last-projects/last-projects.graphql.ts
  mobile/src/screens/last-projects/last-projects.service.tsx
  mobile/src/types/project.ts
  server/src/models/Project.ts
  server/src/resolvers/ProjectResolver.ts
  server/src/resolvers/args/FileProjectArgs.ts
  server/src/resolvers/args/ProjectArgs.ts
  server/src/utils/migrations/1691581386772-codenaute.ts
  server/src/utils/seeds/project.seeds.ts
  server/tests/integrations/services/ProjectServices/addToFavorite.integration.test.ts
  server/tests/integrations/services/ProjectServices/findAllProjectsByEditorId.integration.test.ts
  server/tests/integrations/services/ProjectServices/findAllProjectsByFavorites.integration.test.ts
  server/tests/integrations/services/ProjectServices/findAllProjectsByOwner.integration.test.ts
  server/tests/integrations/services/ProjectServices/findAllProjectsByTemplate.integration.test.ts
  server/tests/integrations/services/ProjectServices/findAllPublicProjects.integration.test.ts
  server/tests/integrations/services/ProjectServices/share.integration.test.ts
  server/tests/setup.jest.ts
Labels: development/app

#79 refactor(server): review classes and removed garbage files
  server/src/index.ts
  server/src/models/Member.ts
  server/src/models/Project.ts
  server/src/models/RoutingToken.ts
  server/src/models/base/BaseModel.ts
  server/src/resolvers/MemberResolver.ts
  server/src/resolvers/ProjectResolver.ts
  server/src/resolvers/RoutingTokenResolver.ts
  server/src/resolvers/args/MemberArgs.ts
  server/src/resolvers/args/ProjectArgs.ts
  server/src/resolvers/args/RoutingTokenArgs.ts
  server/src/services/MemberServices.ts
  server/src/services/ProjectServices.ts
  server/src/services/RoutingTokenServices.ts
  server/src/services/SessionServices.ts
  server/src/services/base/BaseServices.ts
  server/src/utils/configs/database.ts
  server/src/utils/configs/server.ts
  server/src/utils/migrations/1691581386772-codenaute.ts
  server/src/utils/migrations/1691588299105-codenaute.ts
  server/src/utils/seeds/project.seeds.ts
  server/tests/integrations/services/MemberServices/deleteAccount.integration.test.ts
  server/tests/integrations/services/MemberServices/followMember.integration.test.ts
  server/tests/integrations/services/MemberServices/updatePassword.integration.test.ts
  server/tests/integrations/services/MemberServices/validEmail.integration.test.ts
  server/tests/integrations/services/ProjectServices/addToFavorite.integration.test.ts
  server/tests/integrations/services/ProjectServices/findAllProjectsByEditorId.integration.test.ts
  server/tests/integrations/services/ProjectServices/findAllProjectsByFavorites.integration.test.ts
  server/tests/integrations/services/ProjectServices/findAllProjectsByTemplate.integration.test.ts
  server/tests/integrations/services/ProjectServices/share.integration.test.ts
  server/tests/integrations/services/RoutingTokensServices/findByToken.integration.test.ts
  server/tests/setup.jest.ts
Labels: development/app

#111 chore: removing garbage imports, properties and configs
  client/src/graphql/__generated__/gql.ts
  client/src/graphql/__generated__/graphql.ts
  client/src/pages/code/code.graphql.ts
  client/src/pages/code/code.service.tsx
  client/src/pages/create-project/create-project.graphql.ts
  client/src/pages/create-project/create-project.page.tsx
  client/src/pages/create-project/create-project.service.tsx
  client/src/types/project.ts
  mobile/src/gql/__generated__/gql.ts
  mobile/src/gql/__generated__/graphql.ts
  mobile/src/screens/last-projects/last-projects.graphql.ts
  server/src/resolvers/MemberResolver.ts
  server/src/resolvers/ProjectResolver.ts
  server/src/resolvers/args/ProjectArgs.ts
  server/src/services/MemberServices.ts
Labels: development/app
